# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_extras', '0004_use_djangos_emailfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
